update output syntax
haya14busa/action-bumpr pull request #36
Opened 2022-11-15 20:32 UTC by nicgrayson

Update output to new style from deprecation warning: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

2022-12-02 21:58 UTC, nicgrayson commented
@haya14busa pinging to make sure you saw this.

2022-12-02 22:33 UTC, shogo82148 requested changes
Can you fix the warning of shellcheck?

2022-12-02 22:33 UTC, shogo82148 commented on entrypoint.sh
> +  echo "skip=true" >> $GITHUB_OUTPUT
```suggestion
  echo "skip=true" >> "$GITHUB_OUTPUT"
```

2022-12-02 22:33 UTC, shogo82148 commented on entrypoint.sh
> +echo "next_version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
```suggestion
echo "current_version=${CURRENT_VERSION}" >> "$GITHUB_OUTPUT"
echo "next_version=${NEXT_VERSION}" >> "$GITHUB_OUTPUT"
```

2022-12-02 22:33 UTC, shogo82148 commented on entrypoint.sh
> +echo "message=${TAG_MESSAGE}" >> $GITHUB_OUTPUT
```suggestion
echo "message=${TAG_MESSAGE}" >> "$GITHUB_OUTPUT"
```

2022-12-02 23:28 UTC, nicgrayson commented on entrypoint.sh
> +echo "message=${TAG_MESSAGE}" >> $GITHUB_OUTPUT
Updated, Thanks!

2022-12-03 00:39 UTC, shogo82148 approved these changes
LGTM. Thanks!

2022-12-03 00:39 UTC, merged